FROM ubuntu:22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    firefox \
    cron \
    curl \
    nano \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    libxml2-dev \
    libxslt1-dev \
    libz-dev \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy application code
COPY requirements.txt ./
COPY nsm.py ./
COPY pocket-ersatz5.py ./
COPY pocket-mailer.py ./
COPY pocket-mailer-epub.py ./
COPY istilldontcareaboutcookies-1.1.4.xpi ./
COPY bypass-paywalls-firefox.xpi ./

# Create persistent storage directory
RUN mkdir -p /app/data && chmod 777 /app/data

# Copy default config files into persistent storage
COPY config.cfg /app/data/
COPY urls.tsv /app/data/
COPY feeds.cfg /app/data/
COPY filter.txt /app/data/

# Declare persistent volume
VOLUME ["/app/data"]

# Install Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

RUN apt update && apt install -y software-properties-common \
    && add-apt-repository -y ppa:mozillateam/ppa \
    && echo 'Package: firefox*' | tee /etc/apt/preferences.d/firefox \
    && echo 'Pin: release o=LP-PPA-mozillateam' | tee -a /etc/apt/preferences.d/firefox \
    && echo 'Pin-Priority: 1001' | tee -a /etc/apt/preferences.d/firefox \
    && apt update && apt install -y firefox \
    && rm -rf /var/lib/apt/lists/*

# Set up cron job to run nsm.py every hour
RUN echo "35 * * * * root /usr/bin/python3 /app/nsm.py" > /etc/cron.d/nsm-cron \
    && chmod 0644 /etc/cron.d/nsm-cron \
    && crontab /etc/cron.d/nsm-cron

# Start cron in foreground
CMD ["cron", "-f"]
